#!/usr/bin/env bash
# Install / update the Neo Launcher extension on the Poco and hot-reload it.
#   ./install.sh            rsync + Reload() over D-Bus (no logout needed after the first install)
#   ./install.sh --enable   also `gnome-extensions enable` (first install: the shell scans the
#                           extension dir only at login, so reboot the phone once after this)
set -euo pipefail
PHONE=${PHONE:-pulp@192.168.10.98}
UUID=neolauncher@yesman.de
SRC=$(cd "$(dirname "$0")" && pwd)/$UUID
DEST=/home/user/.local/share/gnome-shell/extensions/$UUID
glib-compile-schemas --strict --dry-run "$SRC/schemas"
rsync -a --delete --exclude gschemas.compiled "$SRC/" "$PHONE:/tmp/$UUID.stage/"
# icon packs (generated by tools/import-iconpack.py, not in git) live beside the extension
PACKS=$(dirname "$SRC")/iconpacks
if [ -d "$PACKS" ]; then
  rsync -a --delete "$PACKS/" "$PHONE:/tmp/neo-iconpacks.stage/"
  ssh "$PHONE" "sudo install -d -o user -g user -m 755 /home/user/.local/share/neolauncher && sudo rsync -a --delete --chown=user:user /tmp/neo-iconpacks.stage/ /home/user/.local/share/neolauncher/iconpacks/"
fi
ssh "$PHONE" "set -e
  sudo install -d -o user -g user -m 700 /home/user/.local/share/gnome-shell/extensions
  sudo rsync -a --delete --chown=user:user /tmp/$UUID.stage/ $DEST/
  sudo asuser glib-compile-schemas $DEST/schemas
  # the icon cache is keyed by pack, shape, treatments and RENDER_VERSION: wiping it made the shell redraw every icon
  if [ '${WIPE_ICONS:-0}' = 1 ]; then sudo asuser rm -rf /home/user/.cache/neolauncher/icons; fi
  if [ '${1:-}' = '--enable' ]; then sudo asuser sh -c 'XDG_CURRENT_DESKTOP=GNOME gnome-extensions enable $UUID' || true; fi
  sudo asuser gdbus call --session --dest org.gnome.Shell --object-path /de/yesman/NeoLauncher --method de.yesman.NeoLauncher.Reload 2>&1 | tail -1
  sleep 2
  sudo journalctl --since '-15s' --no-pager -o cat _COMM=gnome-shell | grep -iE 'neolauncher|JS ERROR' | tail -12"
